document.getElementById('show-addMoney').addEventListener('click',function(){
  showSectionById('addMoney-form');
});
document.getElementById('show-CashOut').addEventListener('click',function(){
  showSectionById('cashOut-form');
});
document.getElementById('txn-button').addEventListener('click',function(){
  showSectionById('show-txn-history');
});
